cleanup

diff --git a/ez-misc/update b/ez-misc/update
--- a/ez-misc/update
+++ b/ez-misc/update
@@ -5,157 +5,184 @@
 LOGDIR=$HOME/.update/$(date +%F).log
 
 if [[ ! -d "${LOGDIR}" ]]; then
-    mkdir -p $LOGDIR
+    mkdir -p "$LOG" DIR
 fi
 
 as_root () {
     case $USER_ID in
         0)
             true
-            ;;
+        ;;
         *)
             false
-            ;;
+        ;;
     esac
 }
 
 update_neofetch () {
     LOG=$LOGDIR/neofetch
-    echo '' >> $LOG
-    echo '#################################' >> $LOG
-    echo '#################################' >> $LOG
-    echo $(date) >> $LOG
-    echo '' >> $LOG
-    which neofetch >/dev/null
-    if [[ $? != 0 ]]; then
-        echo "Running fresh install.." >> $LOG
-        case $(as_root) in 
-            true)
-                NFP=/usr/local/bin/neofetch
+    {
+        echo ''
+        echo '#################################'
+        echo '#################################'
+        date
+        echo ''
+        which neofetch >/dev/null
+        if [[ $? != 0 ]]; then
+            echo "Running fresh install.."
+            case $(as_root) in
+                true)
+                    NFP=/usr/local/bin/neofetch
                 ;;
-            *)
-                NFP=$HOME/.local/bin/neofetch
+                *)
+                    NFP=$HOME/.local/bin/neofetch
                 ;;
             esac
-    else
-        echo "Found existing neofetch. Upgrading..." >> $LOG 
-        NFP=$(which neofetch)
-        sudo rm -fv $NFP >> $LOG
-    fi
-    curl -s https://raw.githubusercontent.com/dylanaraps/neofetch/master/neofetch -o $NFP >> $LOG
-    sudo chmod -v 555 $NFP >> $LOG
-    echo "Done!"
+        else
+            echo "Found existing neofetch. Upgrading..."
+            NFP=$(which neofetch)
+            sudo rm -fv "$NFP"
+        fi
+        curl -s https://raw.githubusercontent.com/dylanaraps/neofetch/master/neofetch -o "$NFP"
+        sudo chmod -v 555 "$NFP"
+        echo "Done!"
+    } >> "$LOG"
     exit 0
 }
 
 update_yay () {
     LOG=$LOGDIR/yay
-    echo '' >> $LOG
-    echo '#################################' >> $LOG
-    echo '#################################' >> $LOG
-    echo $(date) >> $LOG
-    echo '' >> $LOG
-    which yay >/dev/null >> $LOG
-    if [[ $? != 0 ]]; then
-        sudo pacman -Sy --noconfirm yay >> $LOG
-    else 
-        sudo yay -Syyu --noconfirm >> $LOG
-    fi
+    {
+        echo ''
+        echo '#################################'
+        echo '#################################'
+        date
+        echo ''
+        which yay > /dev/null
+        if [[ $? != 0 ]]; then
+            sudo pacman -Sy --noconfirm yay
+        else
+            sudo yay -Syyu --noconfirm
+        fi
+    } >> "$LOG"
 }
 
 update_pacman () {
     LOG=$LOGDIR/pacman
-    echo '' >> $LOG
-    echo '#################################' >> $LOG
-    echo '#################################' >> $LOG
-    echo $(date) >> $LOG
-    echo '' >> $LOG
-    sudo pacman -Syyu --noconfirm >> $LOG
+    {
+        echo ''
+        echo '#################################'
+        echo '#################################'
+        date
+        echo ''
+        sudo pacman -Syyu --noconfirm
+    } >> "$LOG"
     sudo reboot
 }
 
 update_dnf () {
     LOG=$LOGDIR/dnf
-    echo '' >> $LOG
-    echo '#################################' >> $LOG
-    echo '#################################' >> $LOG
-    echo $(date) >> $LOG
-    echo '' >> $LOG
-    which dnf >/dev/null
-    if [[ $? != 0 ]]; then
-        sudo yum -y install dnf >> $LOG
-    fi
-    sudo dnf clean all
-    sudo dnf -y upgrade --refresh >> $LOG
+    {
+        echo ''
+        echo '#################################'
+        echo '#################################'
+        date
+        echo ''
+        which dnf >/dev/null
+        if [[ $? != 0 ]]; then
+            sudo yum -y install dnf
+        fi
+        sudo dnf clean all
+        sudo dnf -y upgrade --refresh
+    } >> "$LOG"
     sudo reboot
 }
 
 update_apt () {
     LOG=$LOGDIR/apt
-    echo '' >> $LOG
-    echo '#################################' >> $LOG
-    echo '#################################' >> $LOG
-    echo $(date) >> $LOG
-    echo '' >> $LOG
-    sudo apt -y update  >> $LOG
-    sudo apt -y upgrade >> $LOG
+    {
+        echo ''
+        echo '#################################'
+        echo '#################################'
+        date
+        echo ''
+        sudo apt -y update
+        sudo apt -y upgrade
+        sudo apt autoremove
+    } >> "$LOG"
     sudo reboot
 }
 
 update_brew () {
     LOG=$LOGDIR/brew
-    echo '' >> $LOG
-    echo '#################################' >> $LOG
-    echo '#################################' >> $LOG
-    echo $(date) >> $LOG
-    echo '' >> $LOG
+    {
+        echo ''
+        echo '#################################'
+        echo '#################################'
+        date
+        echo ''
+    } >> "$LOG"
     which brew >/dev/null
     if [[ $? != 0 ]]; then
-        xcode-select --install >> $LOG
-        bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" >> $LOG
+        {
+            xcode-select --install
+            bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+        } >> "$LOG"
         echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zshrc
         eval "$(/opt/homebrew/bin/brew shellenv)"
     else
-        brew update >> $LOG
-        brew upgrade >> $LOG
+        {
+            brew update
+            brew upgrade
+        } >> "$LOG"
     fi
 }
 
 update_ga () {
     LOG=$LOGDIR/ga
-    echo '' >> $LOG
-    echo '#################################' >> $LOG
-    echo '#################################' >> $LOG
-    echo $(date) >> $LOG
-    echo '' >> $LOG
-    mkdir -v $HOME/inst >> $LOG
+    {
+        echo ''
+        echo '#################################'
+        echo '#################################'
+        date
+        echo ''
+        mkdir -pv $HOME/inst
+    } >> "$LOG"
     update_brew
-    brew install autoconf automake libtool libqrencode
-    cd $HOME/inst
-    git clone git@github.com:/google/google-authenticator-libpam >> $LOG
-    cd google-authenticator-libpam
-    ./bootstrap.sh >> $LOG
-    ./configure >> $LOG
-    make >> $LOG
-    sudo make install >> $LOG
-    cd -
-    rm -rfv $HOME/inst >> $LOG
+    {
+        brew install autoconf automake libtool libqrencode
+        cd "$HOME/inst" || exit 1
+        git clone git@github.com:/google/google-authenticator-libpam
+        cd ./google-authenticator-libpam ||exit 1
+        ./bootstrap.sh
+        ./configure
+        make
+        sudo make install
+        cd - || exit 1
+        rm -rfv "$HOME/inst"
+    } >> "$LOG"
     SSH_CONFIG_FILE=/etc/ssh/sshd_config.d/100-macos.conf
-    echo ""
-    echo "PubkeyAuthentication yes" | sudo tee -a $SSH_CONFIG_FILE >> $LOG
-    echo "ChallengeResponseAuthentication yes" | sudo tee -a $SSH_CONFIG_FILE >> $LOG
-    echo "AuthenticationMethods publickey,password publickey,keyboard-interactive:pam" | sudo tee -a $SSH_CONFIG_FILE >> $LOG
-    echo "auth required /usr/local/lib/security/pam_google_authenticator.so nullok" | sudo tee -a /etc/pam.d/sshd >> $LOG
+    {
+        echo ""
+        {
+            echo "PubkeyAuthentication yes"
+            echo "ChallengeResponseAuthentication yes"
+            echo "AuthenticationMethods publickey,password publickey,keyboard-interactive:pam"
+        } | sudo tee -a "$SSH_CONFIG_FILE"
+        echo "auth required /usr/local/lib/security/pam_google_authenticator.so nullok" | sudo tee -a /etc/pam.d/sshd
+    } >> "$LOG"
 }
 
 update_macos () {
     LOG=$LOGDIR/OSX
-    echo '' >> $LOG
-    echo '#################################' >> $LOG
-    echo '#################################' >> $LOG
-    echo $(date) >> $LOG
-    echo '' >> $LOG
-    sudo softwareupdate -i --all --agree-to-license --force -R >> $LOG
+    {
+        echo ''
+        echo '#################################'
+        echo '#################################'
+        date
+        echo ''
+        sudo softwareupdate -i --all --agree-to-license --force -R
+    } >> "$LOG"
 }
 
 get_distro () {
@@ -163,17 +190,17 @@ get_distro () {
         # freedesktop.org and systemd
         . /etc/os-release
         export OS=$ID
-    elif type lsb_release >/dev/null 2>&1; then
+        elif type lsb_release >/dev/null 2>&1; then
         # linuxbase.org
         export OS=$(lsb_release -si | grep -Eo '^[^ ]+' | tr '[:upper:]' '[:lower:]')
-    elif [ -f /etc/lsb-release ]; then
+        elif [ -f /etc/lsb-release ]; then
         # For some versions of Debian/Ubuntu without lsb_release command
         . /etc/lsb-release
         export OS=$(echo $DISTRIB_ID | grep -Eo '^[^ ]+' | tr '[:upper:]' '[:lower:]')
-    elif [ -f /etc/debian_version ]; then
+        elif [ -f /etc/debian_version ]; then
         # Older Debian/Ubuntu/etc.
         export OS=debian
-    elif [ -f /etc/redhat-release ]; then
+        elif [ -f /etc/redhat-release ]; then
         # Older Red Hat, CentOS, etc.
         export OS=$(cat /etc/redhat-release | grep -Eo '^[^ ]+' | tr '[:upper:]' '[:lower:]')
     else
@@ -184,47 +211,49 @@ get_distro () {
 
 update_self () {
     LOG=$LOGDIR/update_script_self
-    echo '' >> $LOG
-    echo '#################################' >> $LOG
-    echo '#################################' >> $LOG
-    echo $(date) >> $LOG
-    echo '' >> $LOG
-    echo "Updating update script.." >> $LOG
-    sudo rm -fv ${LBIN}/update >> $LOG
-    curl https://raw.githubusercontent.com/datflowts/fcknlazyflow/master/ez-misc/update | tee ${LBIN}/update >/dev/null
-    chmod -v 555 ${LBIN}/update >> $LOG
-    echo "Done!"
+    {
+        echo ''
+        echo '#################################'
+        echo '#################################'
+        date
+        echo ''
+        echo "Updating update script.."
+        sudo rm -fv "${LBIN}/update"
+        curl https://raw.githubusercontent.com/datflowts/fcknlazyflow/master/ez-misc/update | tee "${LBIN}/update" >/dev/null
+        chmod -v 555 "${LBIN}/update"
+        echo "Done!"
+    } >> "$LOG"
     exit 0
 }
 
 get_distro
 
 if [[ $# -eq 0 ]] || [[ -z "$1" ]]; then
-    case $OS in 
+    case $OS in
         fedora|centos|rhel|rocky|oracle)
             update_dnf
-            ;;
+        ;;
         ubuntu|debian)
             update_apt
-            ;;
+        ;;
         manjaro|arch)
             update_yay
             update_pacman
-            ;;
+        ;;
         darwin)
             update_brew
             update_macos
-            ;;
+        ;;
         *)
             echo "$OS not supported. Exiting..."
             exit 1
-            ;;
+        ;;
     esac
 else
     case $@ in
         neofetch)
             update_neofetch
-            ;;
+        ;;
         ga|google-authenticator|gauth|google-auth)
             if [[ "$OS" != "darwin" ]]; then
                 echo "This is designed for MacOS only."
@@ -233,10 +262,10 @@ else
                 exit 1
             fi
             update_ga
-            ;;
+        ;;
         yay)
             update_yay
-            ;;
+        ;;
         brew|homebrew)
             which brew >> /dev/null
             if [[ "$OS" != "darwin" ]]; then
@@ -248,13 +277,13 @@ else
                 exit 1
             fi
             update_brew
-            ;;
+        ;;
         self|update)
             update_self
-            ;;
+        ;;
         *)
             echo "Unknown argument. Exiting..."
             exit 1
-            ;;
+        ;;
     esac
 fi
diff --git a/ez-ssh/bridged b/ez-ssh/bridged
--- a/ez-ssh/bridged
+++ b/ez-ssh/bridged
@@ -30,151 +30,152 @@ SSHPORT=22                    # in case it's not the default port where the SSH 
 PATTERN='^[-][[:lower:]_]([[:lower:]0-9_-]{0,31}|[[:lower:]0-9_-]{0,30}\$)$'
 
 case $1 in
-help|h)
-	case $2 in
-	X11)
-		echo "Usage: '$CMD X11 [-username] <command>'"
-		;;
-	ssh)
-		echo "Usage: '$CMD [-username] [command]'"
-		;;
-	tun|tunnel)
-		echo "Usage: '$CMD [-username]'"
-		;;
-	vnc)
-		echo "Usage: '$CMD vnc [-username]'"
-		;;
-	cp)
-		echo "Usage: '$CMD cp [-username] <local file/dir> /<remote dir>"
-		echo "Or: '$CMD cp [-username] -r /<remote file/dir> <local dir>'"
-		echo "Always use relative path for remote file or directory"
-		;;
-	rmkey)
-		echo "Usage: $CMD rmkey [b|h]"
-		echo "Removes known host key for bridge(b) or host(h) - default is host"
-		;;
-	*)
-		echo "---- #### ---- '$CMD' HELP ---- #### ----"
-		echo ""
-		echo "This script is for using to connect to a remote host"
-		echo "which is not directly accessible via SSH"
-		echo "because it's not using the default port while other"
-		echo "ports are blocked locally or it's just not accessible from"
-		echo "outside its private network."
-		echo ""
-		echo "You'll still need another host accessible via SSH default port"
-		echo "in the remote network."
-		echo ""
-		echo " ---- #### ----- 	    EXAMPLES      ----- #### ----"
-		echo " - '$CMD vnc' => VNC to $HOST via SSH Tunnel"
-		echo "    between Ports $TUNPORT and $VNCPORT via"
-		echo "    $BRIDGEHST on $BRIDGEPORT"
-		echo " - '$CMD X11 -foo firefox' => X11-Forward Firefox"
-		echo " - '$CMD -bar' => SSH to $HOST as bar'"
-		echo " - '$CMD foobar => runs 'foobar' as $DEFUSER"
-		echo " - '$CMD cp -foo bar /foobar =>"
-		echo "    copies recursively from bar to /foobar"
-		echo " - '$CMD' => SSH to $HOST as $DEFUSER"
-		echo "--------------------------------------------------------"
-		;;
-	esac
-	;;
-vnc)
-	VNCUSR=$DEFUSER
-	if [[ "$2" =~ $PATTERN ]]; then
-		VNCUSR=${2:1}
-	fi
-	ssh -L ${BRIDGEPORT}:${HOST}:${SSPORT} -N -f ${VNCUSR}@${BRIDGEHST}
-	ssh -L ${TUNPORT}:localhost:${VNCPORT} -N -f -p ${BRIDGEPORT} ${VNCUSR}@localhost
-	if [[ "$(uname)" = "Darwin" ]]; then
-		open vnc://localhost:${TUNPORT} &
-	else
-		which remmina
-		if [[ $? = 0 ]]; then
-			if [[ ! -d "${HOME}/.local/share/remmina" ]]; then
-				mkdir -p "${HOME}/.local/share/remmina"
-			fi
-			RFILE="${HOME}/.local/share/remmina/${CMD}_localhost-${VNCPORT}.remmina"
-			if [[ ! -f "$RFILE" ]]; then
-				touch "$RFILE"
-				{
-					echo "[remmina]",
-					echo "name=${HOST}",
-					echo "disableserverbell=0",
-					echo "showcursor=0",
-					echo "enable-autostart=0",
-					echo "server=localhost:${TUNPORT}",
-					echo "colordepth=32",
-					echo "ssh_tunnel_enabled=0",
-					echo "scale=1",
-					echo "quality=9",
-					echo "disableencryption=0",
-					echo "username=${VNCUSR}",
-					echo "password=.",
-					echo "ssh_tunnel_loopback=0",
-					echo "disablepasswordstoring=1",
-					echo "window_maximize=0",
-					echo "viewmode=4",
-					echo "viewonly=0",
-					echo "window_height=480",
-					echo "ssh_tunnel_auth=0",
-					echo "window_width=640",
-					echo "protocol=VNC",
-					echo "ignore-tls-errors=1",
-					echo "disableclipboard=0",
-					echo "disableserverinput=0" ,
-				} >> "$RFILE"
-			fi
-			remmina -c "$RFILE" >/dev/null 2>&1 &
-		else
-			vncviewer localhost:${TUNPORT} &
-		fi
-	fi
-	;;
-X11)
-	if [[ "$2" =~ $PATTERN ]]; then
-		ssh -J ${2:1}@${BRIDGEHST} -X ${2:1}@${HOST} "$3"
-	else
-		ssh -J ${DEFUSER}@${BRIDGEHST} -X ${DEFUSER}@${HOST} "$2"
-	fi
-	;;
-"${PATTERN}")
-	ssh -J ${1:1}@$BRIDGEHST ${1:1}@${HOST} "$2"
-	;;
-cp)
-	if [[ "$2" = "-r" ]]; then
-		ssh -L ${BRIDGEPORT}:${HOST}:${SSHPORT} -N -f ${DEFUSER}@${BRIDGEHST}
-		scp -r ${DEFUSER}@${HOST}:${3} $4
-	elif [[ "$2" =~ $PATTERN ]]; then
-		ssh -L ${BRIDGEPORT}:${HOST}:${SSHPORT} -N -f ${2:1}@${BRIDGEHST}
-		if [[ "$3" = "-r" ]]; then
-			scp -r ${2:1}@${HOST}:${4} $5
-		else
-			scp -r $4 ${2:1}@${HOST}:${5}
-		fi
-	else
-		ssh -L ${BRIDGEPORT}:${HOST}:${SSHPORT} -N -f ${DEFUSER}@${BRIDGEHST}
-		scp -r $2 ${DEFUSER}@${HOST}:${3}
-	fi
-	;;
-rmkey)
-	case $2 in
-	b|bridge)
-		ssh-keygen -R $BRIDGEHST
-		;;
-	h|host)
-		ssh-keygen -R $HOST
-		;;
-	*)
-		echo "Invalid Argument '$2'"
-		echo "See: '$CMD help rmkey'"
-		;;
-	esac
-	;;
-tun|tunnel)
-	ssh -L ${BRIDGEPORT}:${HOST}:${SSHPORT} -N -f ${DEFUSER}@${BRIDGEHST} &
-	;;
-*)
-	ssh -J ${DEFUSER}@${BRIDGEHST} ${DEFUSER}@${HOST} "$1"
-	;;
+    help|h)
+        case $2 in
+            X11)
+                echo "Usage: '$CMD X11 [-username] <command>'"
+            ;;
+            ssh)
+                echo "Usage: '$CMD [-username] [command]'"
+            ;;
+            tun|tunnel)
+                echo "Usage: '$CMD [-username]'"
+            ;;
+            vnc)
+                echo "Usage: '$CMD vnc [-username]'"
+            ;;
+            cp)
+                echo "Usage: '$CMD cp [-username] <local file/dir> /<remote dir>"
+                echo "Or: '$CMD cp [-username] -r /<remote file/dir> <local dir>'"
+                echo "Always use relative path for remote file or directory"
+            ;;
+            rmkey)
+                echo "Usage: $CMD rmkey [b|h]"
+                echo "Removes known host key for bridge(b) or host(h) - default is host"
+            ;;
+            *)
+                echo "---- #### ---- '$CMD' HELP ---- #### ----"
+                echo ""
+                echo "This script is for using to connect to a remote host"
+                echo "which is not directly accessible via SSH"
+                echo "because it's not using the default port while other"
+                echo "ports are blocked locally or it's just not accessible from"
+                echo "outside its private network."
+                echo ""
+                echo "You'll still need another host accessible via SSH default port"
+                echo "in the remote network."
+                echo ""
+                echo " ---- #### ----- 	    EXAMPLES      ----- #### ----"
+                echo " - '$CMD vnc' => VNC to $HOST via SSH Tunnel"
+                echo "    between Ports $TUNPORT and $VNCPORT via"
+                echo "    $BRIDGEHST on $BRIDGEPORT"
+                echo " - '$CMD X11 -foo firefox' => X11-Forward Firefox"
+                echo " - '$CMD -bar' => SSH to $HOST as bar'"
+                echo " - '$CMD foobar => runs 'foobar' as $DEFUSER"
+                echo " - '$CMD cp -foo bar /foobar =>"
+                echo "    copies recursively from bar to /foobar"
+                echo " - '$CMD' => SSH to $HOST as $DEFUSER"
+                echo "--------------------------------------------------------"
+            ;;
+        esac
+    ;;
+    vnc)
+        VNCUSR=$DEFUSER
+        if [[ "$2" =~ $PATTERN ]]; then
+            VNCUSR=${2:1}
+        fi
+        ssh -L ${BRIDGEPORT}:${HOST}:${SSPORT} -N -f ${VNCUSR}@${BRIDGEHST}
+        ssh -L ${TUNPORT}:localhost:${VNCPORT} -N -f -p ${BRIDGEPORT} ${VNCUSR}@localhost
+        if [[ "$(uname)" = "Darwin" ]]; then
+            open vnc://localhost:${TUNPORT} &
+        else
+            which remmina
+            if [[ $? = 0 ]]; then
+                if [[ ! -d "${HOME}/.local/share/remmina" ]]; then
+                    mkdir -p "${HOME}/.local/share/remmina"
+                fi
+                RFILE="${HOME}/.local/share/remmina/${CMD}_localhost-${VNCPORT}.remmina"
+                if [[ ! -f "$RFILE" ]]; then
+                    touch "$RFILE"
+                    {
+                        echo "[remmina]",
+                        echo "name=${HOST}",
+                        echo "disableserverbell=0",
+                        echo "showcursor=0",
+                        echo "enable-autostart=0",
+                        echo "server=localhost:${TUNPORT}",
+                        echo "colordepth=32",
+                        echo "ssh_tunnel_enabled=0",
+                        echo "scale=1",
+                        echo "quality=9",
+                        echo "disableencryption=0",
+                        echo "username=${VNCUSR}",
+                        echo "password=.",
+                        echo "ssh_tunnel_loopback=0",
+                        echo "disablepasswordstoring=1",
+                        echo "window_maximize=0",
+                        echo "viewmode=4",
+                        echo "viewonly=0",
+                        echo "window_height=480",
+                        echo "ssh_tunnel_auth=0",
+                        echo "window_width=640",
+                        echo "protocol=VNC",
+                        echo "ignore-tls-errors=1",
+                        echo "disableclipboard=0",
+                        echo "disableserverinput=0" ,
+                    } >> "$RFILE"
+                fi
+                remmina -c "$RFILE" >/dev/null 2>&1 &
+            else
+                vncviewer localhost:${TUNPORT} &
+            fi
+        fi
+    ;;
+    X11)
+        if [[ "$2" =~ $PATTERN ]]; then
+            ssh -J ${2:1}@${BRIDGEHST} -X ${2:1}@${HOST} "$3"
+        else
+            ssh -J ${DEFUSER}@${BRIDGEHST} -X ${DEFUSER}@${HOST} "$2"
+        fi
+    ;;
+    "${PATTERN}")
+        ssh -J ${1:1}@$BRIDGEHST ${1:1}@${HOST} "$2"
+    ;;
+    cp)
+        if [[ "$2" = "-r" ]]; then
+            ssh -L ${BRIDGEPORT}:${HOST}:${SSHPORT} -N -f ${DEFUSER}@${BRIDGEHST}
+            scp -r ${DEFUSER}@${HOST}:${3} $4
+            elif [[ "$2" =~ $PATTERN ]]; then
+            ssh -L ${BRIDGEPORT}:${HOST}:${SSHPORT} -N -f ${2:1}@${BRIDGEHST}
+            if [[ "$3" = "-r" ]]; then
+                scp -r ${2:1}@${HOST}:${4} $5
+            else
+                scp -r $4 ${2:1}@${HOST}:${5}
+            fi
+        else
+            ssh -L ${BRIDGEPORT}:${HOST}:${SSHPORT} -N -f ${DEFUSER}@${BRIDGEHST}
+            scp -r $2 ${DEFUSER}@${HOST}:${3}
+        fi
+    ;;
+    rmkey)
+        case $2 in
+            b|bridge)
+                ssh-keygen -R $BRIDGEHST
+            ;;
+            h|host)
+                ssh-keygen -R $HOST
+            ;;
+            *)
+                echo "Invalid Argument '$2'"
+                echo "See: '$CMD help rmkey'"
+            ;;
+        esac
+    ;;
+    tun|tunnel)
+        ssh -L ${BRIDGEPORT}:${HOST}:${SSHPORT} -N -f ${DEFUSER}@${BRIDGEHST} &
+        echo "Tunnel established! Use 'ssh [${DEFUSER}@]localhost:${BRIDGEPORT}' to open a session."
+    ;;
+    *)
+        ssh -p $SSHPORT -J ${DEFUSER}@${BRIDGEHST} ${DEFUSER}@${HOST} "$1"
+    ;;
 esac
